# Generated by Django 6.0.4 on 2026-06-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('created_at', 'last_name')},
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=50),
        ),
    ]
