# Generated by Django 6.0.4 on 2026-04-27 11:36

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='workspaces.workspace')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ('name', 'created_at', 'updated_at', 'workspace'),
            },
        ),
        migrations.CreateModel(
            name='CompanyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_emails', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_notes', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='globally_unique_employment_type')],
            },
        ),
        migrations.CreateModel(
            name='JobBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, default='', max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_benefits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='', max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='globally_unique_job_site')],
            },
        ),
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, default='', max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('min_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('max_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('job_position_ad_url', models.URLField(blank=True, null=True)),
                ('job_location_url', models.URLField(blank=True, null=True)),
                ('job_portal_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal_username', models.CharField(blank=True, max_length=150, null=True)),
                ('portal_password', models.CharField(blank=True, max_length=150, null=True)),
                ('benefits', models.ManyToManyField(blank=True, related_name='job_positions', to='companies.jobbenefit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='companies.company')),
                ('employment_types', models.ManyToManyField(related_name='job_positions', to='companies.employmenttype')),
                ('requirements', models.ManyToManyField(related_name='job_positions', to='companies.jobrequirement')),
                ('job_sites', models.ManyToManyField(related_name='job_positions', to='companies.jobsite')),
                ('tasks', models.ManyToManyField(related_name='job_positions', to='companies.jobtask')),
            ],
            options={
                'ordering': ['company', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['workspace', 'name'], name='companies_c_workspa_2b8567_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('workspace'), name='unique_company_name_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='companyemail',
            index=models.Index(fields=['company'], name='companies_c_company_a039f5_idx'),
        ),
        migrations.AddIndex(
            model_name='companyemail',
            index=models.Index(fields=['company', 'title'], name='companies_c_company_8286a8_idx'),
        ),
        migrations.AddIndex(
            model_name='companyemail',
            index=models.Index(fields=['company', 'email'], name='companies_c_company_f81119_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyemail',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), django.db.models.functions.text.Lower('title'), models.F('company'), name='unique_company_email_and_title_per_company'),
        ),
        migrations.AddIndex(
            model_name='companynote',
            index=models.Index(fields=['company'], name='companies_c_company_8576c5_idx'),
        ),
        migrations.AddIndex(
            model_name='companynote',
            index=models.Index(fields=['company', 'title'], name='companies_c_company_940da6_idx'),
        ),
        migrations.AddConstraint(
            model_name='companynote',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('company'), name='unique_note_title_per_company'),
        ),
        migrations.AddConstraint(
            model_name='jobbenefit',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('description'), models.F('user'), name='unique_job_benefit_per_user'),
        ),
        migrations.AddConstraint(
            model_name='jobrequirement',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('description'), django.db.models.functions.text.Lower('title'), models.F('user'), name='unique_job_requirement_per_user'),
        ),
        migrations.AddIndex(
            model_name='jobtask',
            index=models.Index(fields=['title'], name='companies_j_title_a643c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobtask',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), django.db.models.functions.text.Lower('description'), models.F('user'), name='unique_job_task_per_user'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['company'], name='companies_j_company_5c2ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['company', 'title'], name='companies_j_company_399367_idx'),
        ),
    ]
