# Generated by Django 6.0.4 on 2026-05-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_jobbenefit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobbenefit',
            name='description',
            field=models.TextField(blank=True, default='', max_length=60),
        ),
    ]
