# Generated by Django 6.0.4 on 2026-05-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyemail',
            options={'ordering': ('company', 'title')},
        ),
        migrations.AlterModelOptions(
            name='companynote',
            options={'ordering': ('company', 'title')},
        ),
        migrations.AlterModelOptions(
            name='jobbenefit',
            options={'ordering': ('user', 'name')},
        ),
        migrations.AlterModelOptions(
            name='jobrequirement',
            options={'ordering': ('user', 'title')},
        ),
        migrations.AlterModelOptions(
            name='jobtask',
            options={'ordering': ('user', 'title')},
        ),
    ]
