# Generated by Django 6.0.4 on 2026-07-04 13:17

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_companyemail_options_alter_companynote_options_and_more'),
        ('workspaces', '0002_alter_workspace_unique_workspace_name_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmenttype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='jobposition',
            options={'ordering': ('company', 'title')},
        ),
        migrations.AlterConstraint(
            model_name='company',
            name='unique_company_name_per_workspace',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('workspace'), name='unique_company_name_per_workspace', violation_error_code='duplicate_company_name', violation_error_message='A company with this name already exists in the workspace.'),
        ),
        migrations.AlterConstraint(
            model_name='companyemail',
            name='unique_company_email_and_title_per_company',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), django.db.models.functions.text.Lower('title'), models.F('company'), name='unique_company_email_and_title_per_company', violation_error_code='duplicate_company_email', violation_error_message='A company email with this email address and title already exists in the company.'),
        ),
        migrations.AlterConstraint(
            model_name='companynote',
            name='unique_note_title_per_company',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('company'), name='unique_note_title_per_company', violation_error_code='duplicate_company_note_title', violation_error_message='A company note with this title already exists in the company.'),
        ),
        migrations.AlterConstraint(
            model_name='employmenttype',
            name='globally_unique_employment_type',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='globally_unique_employment_type', violation_error_code='duplicate_employment_type_name', violation_error_message='An employment type with this name already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='jobbenefit',
            name='unique_job_benefit_per_user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('description'), models.F('user'), name='unique_job_benefit_per_user', violation_error_code='duplicate_job_benefit', violation_error_message='A job benefit with this name and description already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='jobrequirement',
            name='unique_job_requirement_per_user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('description'), django.db.models.functions.text.Lower('title'), models.F('user'), name='unique_job_requirement_per_user', violation_error_code='duplicate_job_requirement', violation_error_message='A job requirement with this title and description already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='jobsite',
            name='globally_unique_job_site',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='globally_unique_job_site', violation_error_code='duplicate_job_site_name', violation_error_message='A job site with this name already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='jobtask',
            name='unique_job_task_per_user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), django.db.models.functions.text.Lower('description'), models.F('user'), name='unique_job_task_per_user', violation_error_code='duplicate_job_task', violation_error_message='A job task with this title and description already exists.'),
        ),
    ]
