# Generated by Django 6.0.4 on 2026-07-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_employmenttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsite',
            options={'ordering': ('name',)},
        ),
    ]
