# Generated by Django 6.0.4 on 2026-07-11 19:02

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_jobsite_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobrequirement',
            name='unique_job_requirement_per_user',
        ),
        migrations.AddConstraint(
            model_name='jobrequirement',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), django.db.models.functions.text.Lower('description'), models.F('user'), name='unique_job_requirement_per_user', violation_error_code='duplicate_job_requirement', violation_error_message='A job requirement with this title and description already exists.'),
        ),
    ]
