# Generated by Django 6.0.4 on 2026-07-09 18:40

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documenttype_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('owner', 'name', 'created_at', 'updated_at')},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ('name', 'owner')},
        ),
        migrations.AlterConstraint(
            model_name='document',
            name='unique_document_name_per_user',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_document_name_per_user', violation_error_code='duplicate_document_name', violation_error_message='A document with this name already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='documenttype',
            name='unique_document_type_per_user',
            constraint=models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('name'), name='unique_document_type_per_user', violation_error_code='duplicate_type_document_name', violation_error_message='A document type with this name already exists.'),
        ),
    ]
