# Generated by Django 6.0.4 on 2026-07-11 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options_alter_documenttype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('owner', 'file_hash'), name='unique_document_file_per_user', violation_error_code='duplicate_document', violation_error_message='The uploaded file already exists.'),
        ),
    ]
