# Generated by Django 6.0.4 on 2026-06-29 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='workspace',
            name='unique_workspace_name_per_user',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_workspace_name_per_user', violation_error_code='duplicate_workspace_name', violation_error_message='A workspace already exists with this name'),
        ),
    ]
