# Generated by Django 6.0.4 on 2026-04-27 11:36

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('documents', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Pending', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=1, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Application Statuses',
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('label'), name='globally_unique_application_status')],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='job_applications', to='documents.document')),
                ('emails', models.ManyToManyField(related_name='job_applications', to='companies.companyemail')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='companies.jobposition')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.applicationstatus')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-date_applied', 'owner', 'workspace', 'job_position'),
            },
        ),
        migrations.CreateModel(
            name='JobApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application_notes', to='applications.jobapplication')),
            ],
            options={
                'ordering': ('job_application', 'title'),
            },
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['owner'], name='application_owner_i_47ad0f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['owner', 'workspace'], name='application_owner_i_5418b2_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['owner', 'workspace', 'job_position'], name='application_owner_i_a6693c_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('owner', 'workspace', 'job_position'), name='unique_job_application_for_each_job_position_in_the_same_workspace_for_the_user'),
        ),
        migrations.AddConstraint(
            model_name='jobapplicationnote',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('job_application'), name='unique_job_application_note_per_job_application'),
        ),
    ]
