# Generated by Django 6.0.4 on 2026-05-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('companies', '0008_alter_companyemail_options_alter_companynote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='date_applied',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='emails',
            field=models.ManyToManyField(blank=True, related_name='job_applications', to='companies.companyemail'),
        ),
        migrations.AlterField(
            model_name='jobapplicationnote',
            name='title',
            field=models.TextField(max_length=60),
        ),
    ]
