# Generated by Django 6.0.4 on 2026-05-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationstatus_is_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
