# Generated by Django 6.0.4 on 2026-05-27 07:16

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_applicationstatus_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationstatus',
            name='globally_unique_application_status',
        ),
        migrations.AddConstraint(
            model_name='applicationstatus',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('label'), models.F('order'), name='globally_unique_application_status'),
        ),
    ]
