# Generated by Django 6.0.4 on 2026-05-27 07:18

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_applicationstatus_globally_unique_application_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationstatus',
            name='globally_unique_application_status',
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
        migrations.AddConstraint(
            model_name='applicationstatus',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('label'), name='globally_unique_application_status'),
        ),
    ]
