# Generated by Django 6.0.4 on 2026-06-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_applicationstatus_globally_unique_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationnote',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
