# Generated by Django 6.0.4 on 2026-07-11 11:28

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_jobapplicationnote_title'),
        ('companies', '0010_alter_jobsite_options'),
        ('documents', '0004_document_unique_document_file_per_user'),
        ('workspaces', '0002_alter_workspace_unique_workspace_name_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='applicationstatus',
            name='globally_unique_application_status',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('label'), name='globally_unique_application_status', violation_error_code='duplicate_label', violation_error_message='Application status with this label already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='jobapplication',
            name='unique_job_application_for_each_job_position_in_the_same_workspace_for_the_user',
            constraint=models.UniqueConstraint(fields=('owner', 'workspace', 'job_position'), name='unique_job_application_for_each_job_position_in_the_same_workspace_for_the_user', violation_error_code='duplicate_job_application', violation_error_message='Job application for job position already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='jobapplicationnote',
            name='unique_job_application_note_per_job_application',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('job_application'), name='unique_job_application_note_per_job_application', violation_error_code='duplicate_job_application_note', violation_error_message='Job application note with this title already exists.'),
        ),
    ]
